name: Pelican Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Ограничиваем один параллельный деплой
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    with:
      settings: "publishconf.py"